$(document).ready(function(){
  $("#hideSeventh").click(function(){
    $("#seventh").hide();
  });
  $("#showSeventh").click(function(){
    $("#seventh").show();
  });
  $("#hideSeventhHonors").click(function(){
    $("#seventhHonors").hide();
  });
  $("#showSeventhHonors").click(function(){
    $("#seventhHonors").show();
  });
  $("#showEighth").click(function(){
    $("#eighth").show();
  });
  $("#hideEighth").click(function(){
    $("#eighth").hide();
  });
  $("#showEighthHonors").click(function(){
    $("#eighthHonors").show();
  });
  $("#hideEighthHonors").click(function(){
    $("#eighthHonors").hide();
  });
});
