$(document).ready(function(){
  $("#hideSeventh").click(function(){
    $("#seventh").hide();
  });
  $("#showSeventh").click(function(){
    $("#seventh").show();
  });
  $("#hideSeventhHonors").click(function(){
    $("#seventhHonors").hide();
  });
  $("#showSeventhHonors").click(function(){
    $("#seventhHonors").show();
});
